# Generated by Django 2.2.7 on 2023-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TOFEL', models.IntegerField()),
                ('GRE', models.IntegerField()),
                ('UNI_rating', models.IntegerField()),
                ('SOP', models.DecimalField(decimal_places=4, max_digits=4)),
                ('LOR', models.DecimalField(decimal_places=4, max_digits=4)),
                ('CGPA', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Research_Ex', models.BooleanField()),
                ('Chance_of_Admit', models.DecimalField(decimal_places=4, max_digits=4, null=True)),
            ],
        ),
    ]
