# Generated by Django 2.2.7 on 2023-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='CGPA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='Chance_of_Admit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='LOR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='SOP',
            field=models.FloatField(),
        ),
    ]
