# Generated by Django 2.2.7 on 2023-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230602_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='Chance_of_Admit',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
